spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/florist?serverTimezone=GMT%2b8
    username: root
    password: root
  application:
    name: florist
server:
  port: 5000



